## githubiverse-template by Gary Hodgson
## license: GPL3
##
## The data below is left as an example.  Please change each entry to match your requirements. 
## 

## Uses distinct namespace. Jekyll settings should go at the root level.
githubiverse:
    ## Metadata
    title: "UConduit H-Bot as Fulfilled by Terawatt Industries"
    author: Terawatt Industries
    license: Creative Commons Attribution, Share-Alike, 3.0
    tags: [3d printer,calibration,printer parts, calibration cube,cube]

    ## Github project parameters.
    github:
        base: https://github.com/
        user: Terawatt-Industries
        repository: uconduit
        branch: master

    ## The names of directories where any images, source and stl files associated with the project can be found.
    img_dir: img
    stl_dir: STLs
    src_dir:

    ## The headline image
    lead_image: uc_gantry_top.png
    show_lead_image: true

    ## Optional. When uncommented appends the content of the file defined here to the project description.  Any text in index.md, after the yaml header, will be shown first.
    description_file: README.md

    ## Preview the first STL in the list when the page loads.
    autoload_stl: true

    ## Show a github "fork me" ribbon in the top righthand corner of the page.
    show_forkme_ribbon: true